### ISSUE TITLE
Conference talk summary: Privacy AI Startups & the OpenMined Open-source community (panel discussion)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#122]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by kolaisaac** [comment]
@em-blue I will like to take this up

**Comment by em-blue** [comment]
@kolaisaac Awesome, Go for it!

**Comment by kolaisaac** [comment]
Hello Ma, 

I have started the writing, am writing it in a reported speech format. Please can you go over the little have done? So that I can continue or change the writing pattern.

Below is the Link.

Kind regards  

https://docs.google.com/document/d/1iAQTMLKYi0julaHI5s-44yAH7EZNJZjjzFSbo-Z2WxM/edit?usp=sharing
