### ISSUE TITLE
Blog: In case you missed it: Summary blog highlighting content from Patrick's AMA (written using the video recording)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#95]
Write a blog post highlighting the coolest parts from Patrick's Ask Me Anything video (https://www.youtube.com/watch?v=OjrkpdMmv5g)! 
For example, here's what Emma wrote from Ionesio's AMA: https://blog.openmined.org/what-is-pygrid-demo/

**Comment by balapriyac** [comment]
Hi @dwvicy Looks like you've been busy lately.  I also see that you've assigned yourself another issue as well.
Pls let us know if you'd like to pass this to someone.

**Comment by balapriyac** [comment]
@dwvicy I can see that you've assigned yourself another issue #125 as well.
It has been more than six months since you've assigned the issue to yourself. 
Kindly update on the progress of your drafts. I had also reached out to you before a few weeks.
Else, we may have to remove assignment so that other members of the team can work on this.

**Comment by BhaswatiRoy** [comment]
Hello
I would like to work on summarization
It would be great if this issue could be assigned to me
